apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-l2pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.36-192.168.0.45

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-l2pool