apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: media-automation
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled